// <auto-generated />
using System;
using Activity_2__CODE_FIRST_.MODEL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Activity_2__CODE_FIRST_.Migrations
{
    [DbContext(typeof(ClassicModelDbContext))]
    partial class ClassicModelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Activity_2__CODE_FIRST_.MODEL.Customer", b =>
                {
                    b.Property<int?>("CustomerNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdressLine1")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("AdressLine2")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ContactFirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ContactLastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double?>("CreditLimit")
                        .HasColumnType("double");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("SalesRepEmployeeNumber")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CustomerNumber");

                    b.HasIndex("SalesRepEmployeeNumber");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Activity_2__CODE_FIRST_.MODEL.Employee", b =>
                {
                    b.Property<int?>("EmployeeNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Extension")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("JobTitle")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OfficeCode")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int?>("ReportsTo")
                        .HasColumnType("int");

                    b.HasKey("EmployeeNumber");

                    b.HasIndex("OfficeCode");

                    b.HasIndex("ReportsTo");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Activity_2__CODE_FIRST_.MODEL.Office", b =>
                {
                    b.Property<string>("OfficeCode")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("AdressLine1")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("AdressLine2")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("State")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Territory")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("OfficeCode");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("Activity_2__CODE_FIRST_.MODEL.Order", b =>
                {
                    b.Property<int?>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("CustomerNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("RequiredDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("OrderNumber");

                    b.HasIndex("CustomerNumber");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Activity_2__CODE_FIRST_.MODEL.OrderDetail", b =>
                {
                    b.Property<int?>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<short?>("OrderLineNumber")
                        .HasColumnType("smallint");

                    b.Property<double?>("PriceEach")
                        .HasColumnType("double");

                    b.Property<int?>("QuantityOrdered")
                        .HasColumnType("int");

                    b.HasKey("OrderNumber", "ProductCode");

                    b.HasIndex("ProductCode");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Activity_2__CODE_FIRST_.MODEL.Payment", b =>
                {
                    b.Property<int?>("CustomerNumber")
                        .HasColumnType("int");

                    b.Property<string>("CheckNumber")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<double?>("Amount")
                        .HasColumnType("double");

                    b.Property<string>("PaymentDate")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CustomerNumber", "CheckNumber");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Activity_2__CODE_FIRST_.MODEL.Product", b =>
                {
                    b.Property<string>("ProductCode")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<double?>("BuyPrice")
                        .HasColumnType("double");

                    b.Property<double?>("MSRP")
                        .HasColumnType("double");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ProductLine")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ProductName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ProductScale")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ProductVendor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<short?>("QuantityStock")
                        .HasColumnType("smallint");

                    b.HasKey("ProductCode");

                    b.HasIndex("ProductLine");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Activity_2__CODE_FIRST_.MODEL.ProductLines", b =>
                {
                    b.Property<string>("ProductLine")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("HtmlDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TextDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ProductLine");

                    b.ToTable("ProductLiness");
                });

            modelBuilder.Entity("Activity_2__CODE_FIRST_.MODEL.Customer", b =>
                {
                    b.HasOne("Activity_2__CODE_FIRST_.MODEL.Employee", "Employee")
                        .WithMany("Customers")
                        .HasForeignKey("SalesRepEmployeeNumber");
                });

            modelBuilder.Entity("Activity_2__CODE_FIRST_.MODEL.Employee", b =>
                {
                    b.HasOne("Activity_2__CODE_FIRST_.MODEL.Office", "Office")
                        .WithMany("Employees")
                        .HasForeignKey("OfficeCode");

                    b.HasOne("Activity_2__CODE_FIRST_.MODEL.Employee", "ReportedEmployee")
                        .WithMany()
                        .HasForeignKey("ReportsTo");
                });

            modelBuilder.Entity("Activity_2__CODE_FIRST_.MODEL.Order", b =>
                {
                    b.HasOne("Activity_2__CODE_FIRST_.MODEL.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerNumber");
                });

            modelBuilder.Entity("Activity_2__CODE_FIRST_.MODEL.OrderDetail", b =>
                {
                    b.HasOne("Activity_2__CODE_FIRST_.MODEL.Order", "Order")
                        .WithMany("OrdersDetails")
                        .HasForeignKey("OrderNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Activity_2__CODE_FIRST_.MODEL.Product", "Product")
                        .WithMany("OrdersDetails")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Activity_2__CODE_FIRST_.MODEL.Payment", b =>
                {
                    b.HasOne("Activity_2__CODE_FIRST_.MODEL.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Activity_2__CODE_FIRST_.MODEL.Product", b =>
                {
                    b.HasOne("Activity_2__CODE_FIRST_.MODEL.ProductLines", "ProductLines")
                        .WithMany("Products")
                        .HasForeignKey("ProductLine");
                });
#pragma warning restore 612, 618
        }
    }
}
